mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
unified-delay: true
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  nameserver:
  - https://223.5.5.5/dns-query
  - https://1.12.12.12/dns-query
  nameserver-policy:
    geosite:cn,private:
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
    geosite:geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
proxies:
- name: Opera-亚洲1
  type: http
  server: 77.111.245.15
  port: 443
  username: 82A1CB9E85C407B8296F4FBB5DCEF68C6BE5F626
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ3UHJOUm5xNEZubnllU0FEU2dScGVnWWdWMW0yVUQ5b3B2c3pmeXZiblI0IiwieSI6InFBZ0o3SUROSkxUSnJjd0ZlTU1xUE5BNWZNWGpSQWhTX1hXN2xORTNDem8ifX0.DU0RUQSxMmzSJ1ZVnqdOu-toSA2f3TWE5uVB_RxYjh3HhxFZzjj1-g.NP5XrKV0WoU-_pCS.KyWAS8ao99zXKBqM3xaT0EeRqkMeLTukBp7Mt67o3sHUbelZrcFeNlQhc5oM7vIc6asScFIFDwYiMDtW6odAdTD1DUbPfp8MeoHXogw7jUWIiGg15Yu--lMFJsFf-N6LpJjCZFwVaki5Wt8kaHbEniBkMFbwFbssH8sAsRDnt10j7RjiE9ZOtlsbqoH1QkqWLpbsEto3pJ53hg2IqQ3IY7GMmIl6HLQIQDROiAomHaiYzbmnXSf0WY6LKoIxUWrwy_m3Za2FlPoxSKJglRGiHiN0aLmhPSPpZR3AgRA7yevx7NXLREQo7hT2prVefbNddGNN3L_I0xc7iC1_ywR0lNBMvujXnkmDlQ5jp-Okr9YgcvvJvlmPExYJifNDsZkVSjPeQ3j8gV9KS2IdhQywWoMgKAXtksbxjitJSPFgdben_rX12rAKDyaBXUc_P3GXm_9H_7X7x6Y.dJsA2WJpAerPsVktHPbOCQ
  tls: true
  sni: as0.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-亚洲2
  type: http
  server: 77.111.245.11
  port: 443
  username: 82A1CB9E85C407B8296F4FBB5DCEF68C6BE5F626
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ3UHJOUm5xNEZubnllU0FEU2dScGVnWWdWMW0yVUQ5b3B2c3pmeXZiblI0IiwieSI6InFBZ0o3SUROSkxUSnJjd0ZlTU1xUE5BNWZNWGpSQWhTX1hXN2xORTNDem8ifX0.DU0RUQSxMmzSJ1ZVnqdOu-toSA2f3TWE5uVB_RxYjh3HhxFZzjj1-g.NP5XrKV0WoU-_pCS.KyWAS8ao99zXKBqM3xaT0EeRqkMeLTukBp7Mt67o3sHUbelZrcFeNlQhc5oM7vIc6asScFIFDwYiMDtW6odAdTD1DUbPfp8MeoHXogw7jUWIiGg15Yu--lMFJsFf-N6LpJjCZFwVaki5Wt8kaHbEniBkMFbwFbssH8sAsRDnt10j7RjiE9ZOtlsbqoH1QkqWLpbsEto3pJ53hg2IqQ3IY7GMmIl6HLQIQDROiAomHaiYzbmnXSf0WY6LKoIxUWrwy_m3Za2FlPoxSKJglRGiHiN0aLmhPSPpZR3AgRA7yevx7NXLREQo7hT2prVefbNddGNN3L_I0xc7iC1_ywR0lNBMvujXnkmDlQ5jp-Okr9YgcvvJvlmPExYJifNDsZkVSjPeQ3j8gV9KS2IdhQywWoMgKAXtksbxjitJSPFgdben_rX12rAKDyaBXUc_P3GXm_9H_7X7x6Y.dJsA2WJpAerPsVktHPbOCQ
  tls: true
  sni: as1.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-欧洲1
  type: http
  server: 77.111.247.36
  port: 443
  username: 71F73470951033E5DBCDAE96272B96C24261103A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjaW5kbmNZZW1KWUFvZ1RNRUJOTHZqRTZUOXIzTXdXX2lXbHc2ZXgzb2ZrIiwieSI6IlZod3F3NmZYQkh0b1RHb25kZGFKRnI2dzhlVFVHSzhILUU5TFJPTjViM1EifX0.x5KCw31eOwvKksCmFqD9-xf5uLnTCW9bNGy_nvvLAwzIYNxrnpM0Gg.yzMuGVrn56EOLSiS.jWXW__iPRPNe_1HixMq7752pyLQ7ZN949QWy-5_clkqY4oe8lXsIe0JfPllh3Ue2Vfa6rjr1RPVh_RRpeBgqQDgivF60nx-SyKq-dVwikoXBNlJupK6_FbMV3d5p5YRqCVMnl_hpNF0v6RULnHahGcWtbMR_eAx3oOufYoxI7BcblTMzRzA2-5x_H2fGQwDcHXTw-FxJIAqBFJwiqfmnlBTy94iPSe_QgmRyLLcXn6SbvKUL9-tt3TbjbYoHsasKgdbBxQSv_AI9vhkz6xKIlz3LMyuZjOR8etYh9v4UUkb6vDIuQljC_6sjbx9BzyXzS4gAmeymbYQeAxRsR4Iqff5HyI4Oz7u4OLe9cuEWHMIdF6yRWRqw1wf5WCz1OxOcLDR7_EwPPiD_0KOOE1S8aiMcxyLO98gLz8M25IdsXS4JFn4dM73fksdNquAG2cL8DzJ4QoRuUT4.uV559QUr7yBrW1cTHnPEvw
  tls: true
  sni: eu0.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-欧洲2
  type: http
  server: 77.111.247.106
  port: 443
  username: 71F73470951033E5DBCDAE96272B96C24261103A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjaW5kbmNZZW1KWUFvZ1RNRUJOTHZqRTZUOXIzTXdXX2lXbHc2ZXgzb2ZrIiwieSI6IlZod3F3NmZYQkh0b1RHb25kZGFKRnI2dzhlVFVHSzhILUU5TFJPTjViM1EifX0.x5KCw31eOwvKksCmFqD9-xf5uLnTCW9bNGy_nvvLAwzIYNxrnpM0Gg.yzMuGVrn56EOLSiS.jWXW__iPRPNe_1HixMq7752pyLQ7ZN949QWy-5_clkqY4oe8lXsIe0JfPllh3Ue2Vfa6rjr1RPVh_RRpeBgqQDgivF60nx-SyKq-dVwikoXBNlJupK6_FbMV3d5p5YRqCVMnl_hpNF0v6RULnHahGcWtbMR_eAx3oOufYoxI7BcblTMzRzA2-5x_H2fGQwDcHXTw-FxJIAqBFJwiqfmnlBTy94iPSe_QgmRyLLcXn6SbvKUL9-tt3TbjbYoHsasKgdbBxQSv_AI9vhkz6xKIlz3LMyuZjOR8etYh9v4UUkb6vDIuQljC_6sjbx9BzyXzS4gAmeymbYQeAxRsR4Iqff5HyI4Oz7u4OLe9cuEWHMIdF6yRWRqw1wf5WCz1OxOcLDR7_EwPPiD_0KOOE1S8aiMcxyLO98gLz8M25IdsXS4JFn4dM73fksdNquAG2cL8DzJ4QoRuUT4.uV559QUr7yBrW1cTHnPEvw
  tls: true
  sni: eu1.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-欧洲3
  type: http
  server: 77.111.247.29
  port: 443
  username: 71F73470951033E5DBCDAE96272B96C24261103A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjaW5kbmNZZW1KWUFvZ1RNRUJOTHZqRTZUOXIzTXdXX2lXbHc2ZXgzb2ZrIiwieSI6IlZod3F3NmZYQkh0b1RHb25kZGFKRnI2dzhlVFVHSzhILUU5TFJPTjViM1EifX0.x5KCw31eOwvKksCmFqD9-xf5uLnTCW9bNGy_nvvLAwzIYNxrnpM0Gg.yzMuGVrn56EOLSiS.jWXW__iPRPNe_1HixMq7752pyLQ7ZN949QWy-5_clkqY4oe8lXsIe0JfPllh3Ue2Vfa6rjr1RPVh_RRpeBgqQDgivF60nx-SyKq-dVwikoXBNlJupK6_FbMV3d5p5YRqCVMnl_hpNF0v6RULnHahGcWtbMR_eAx3oOufYoxI7BcblTMzRzA2-5x_H2fGQwDcHXTw-FxJIAqBFJwiqfmnlBTy94iPSe_QgmRyLLcXn6SbvKUL9-tt3TbjbYoHsasKgdbBxQSv_AI9vhkz6xKIlz3LMyuZjOR8etYh9v4UUkb6vDIuQljC_6sjbx9BzyXzS4gAmeymbYQeAxRsR4Iqff5HyI4Oz7u4OLe9cuEWHMIdF6yRWRqw1wf5WCz1OxOcLDR7_EwPPiD_0KOOE1S8aiMcxyLO98gLz8M25IdsXS4JFn4dM73fksdNquAG2cL8DzJ4QoRuUT4.uV559QUr7yBrW1cTHnPEvw
  tls: true
  sni: eu2.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-欧洲4
  type: http
  server: 77.111.247.80
  port: 443
  username: 71F73470951033E5DBCDAE96272B96C24261103A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJjaW5kbmNZZW1KWUFvZ1RNRUJOTHZqRTZUOXIzTXdXX2lXbHc2ZXgzb2ZrIiwieSI6IlZod3F3NmZYQkh0b1RHb25kZGFKRnI2dzhlVFVHSzhILUU5TFJPTjViM1EifX0.x5KCw31eOwvKksCmFqD9-xf5uLnTCW9bNGy_nvvLAwzIYNxrnpM0Gg.yzMuGVrn56EOLSiS.jWXW__iPRPNe_1HixMq7752pyLQ7ZN949QWy-5_clkqY4oe8lXsIe0JfPllh3Ue2Vfa6rjr1RPVh_RRpeBgqQDgivF60nx-SyKq-dVwikoXBNlJupK6_FbMV3d5p5YRqCVMnl_hpNF0v6RULnHahGcWtbMR_eAx3oOufYoxI7BcblTMzRzA2-5x_H2fGQwDcHXTw-FxJIAqBFJwiqfmnlBTy94iPSe_QgmRyLLcXn6SbvKUL9-tt3TbjbYoHsasKgdbBxQSv_AI9vhkz6xKIlz3LMyuZjOR8etYh9v4UUkb6vDIuQljC_6sjbx9BzyXzS4gAmeymbYQeAxRsR4Iqff5HyI4Oz7u4OLe9cuEWHMIdF6yRWRqw1wf5WCz1OxOcLDR7_EwPPiD_0KOOE1S8aiMcxyLO98gLz8M25IdsXS4JFn4dM73fksdNquAG2cL8DzJ4QoRuUT4.uV559QUr7yBrW1cTHnPEvw
  tls: true
  sni: eu3.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-美洲1
  type: http
  server: 77.111.246.27
  port: 443
  username: 0535B93B5824BEBA29C3DD19188B86C2807835B6
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCY0x6Z1ZrLUduaEhMYjBzSVpQdm1tdXRHeUk0a2FRMU1JT1luaGZ4cEFJIiwieSI6ImRaTzR1VGNKYVU0Wmxqb08wUnBBWEpzVVF0bGs1OXI2YlFlaXdfV2FsUWMifX0.f6XZz8-B3IHyYG6MVqQbAq1h8YuTWSfHMWtU3hi1268CCkv3SlbcLw.9B1nLoltttlKA_Po.76TDzRUS84ZWnvenCiDiUC8SWueygzTNuECLvpfs_Kdl1F5JLQHYrj2EeGWCO4w80gYk8JIbKYMZZcZInCagjAqWLXGLGS5jLia6_MhbkY0_yXIg3mNRtXgT6ozC0ouJrQSPvlFwoR6ySb-dL9k1ZoX3F4ipqVSv94SMTQB2AsrXjsJWTzLMwDG2P0ybHL8fcXKKQiZQmp_I4wDjYr5ZYnOXe74aidk0I7KcMjbk8NVFCl-ym85Y6_uEFNK7RCxb_NG8RcyNsz5mGgzoJTvylNETNQquFWwiagBe327iP7LMtcsqK_iuIXnSN0ng5jIOF-EH4IHitPHOu4K-yjZS0c4_V0pVSMrrTmfxdj2ZyaeTIbMylrIdelRW0rMOrtoz240XIh4dFrppRcyvKesG7kv-RUYZrY4x0TGSUqfDQiqEFOgDaC21EzCcJ9qiP0XA0wI3Pk2-e1s.RT7Bx8gNvsZXgkV-xLA-tA
  tls: true
  sni: am0.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-美洲2
  type: http
  server: 77.111.246.40
  port: 443
  username: 0535B93B5824BEBA29C3DD19188B86C2807835B6
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCY0x6Z1ZrLUduaEhMYjBzSVpQdm1tdXRHeUk0a2FRMU1JT1luaGZ4cEFJIiwieSI6ImRaTzR1VGNKYVU0Wmxqb08wUnBBWEpzVVF0bGs1OXI2YlFlaXdfV2FsUWMifX0.f6XZz8-B3IHyYG6MVqQbAq1h8YuTWSfHMWtU3hi1268CCkv3SlbcLw.9B1nLoltttlKA_Po.76TDzRUS84ZWnvenCiDiUC8SWueygzTNuECLvpfs_Kdl1F5JLQHYrj2EeGWCO4w80gYk8JIbKYMZZcZInCagjAqWLXGLGS5jLia6_MhbkY0_yXIg3mNRtXgT6ozC0ouJrQSPvlFwoR6ySb-dL9k1ZoX3F4ipqVSv94SMTQB2AsrXjsJWTzLMwDG2P0ybHL8fcXKKQiZQmp_I4wDjYr5ZYnOXe74aidk0I7KcMjbk8NVFCl-ym85Y6_uEFNK7RCxb_NG8RcyNsz5mGgzoJTvylNETNQquFWwiagBe327iP7LMtcsqK_iuIXnSN0ng5jIOF-EH4IHitPHOu4K-yjZS0c4_V0pVSMrrTmfxdj2ZyaeTIbMylrIdelRW0rMOrtoz240XIh4dFrppRcyvKesG7kv-RUYZrY4x0TGSUqfDQiqEFOgDaC21EzCcJ9qiP0XA0wI3Pk2-e1s.RT7Bx8gNvsZXgkV-xLA-tA
  tls: true
  sni: am1.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-美洲3
  type: http
  server: 77.111.246.26
  port: 443
  username: 0535B93B5824BEBA29C3DD19188B86C2807835B6
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCY0x6Z1ZrLUduaEhMYjBzSVpQdm1tdXRHeUk0a2FRMU1JT1luaGZ4cEFJIiwieSI6ImRaTzR1VGNKYVU0Wmxqb08wUnBBWEpzVVF0bGs1OXI2YlFlaXdfV2FsUWMifX0.f6XZz8-B3IHyYG6MVqQbAq1h8YuTWSfHMWtU3hi1268CCkv3SlbcLw.9B1nLoltttlKA_Po.76TDzRUS84ZWnvenCiDiUC8SWueygzTNuECLvpfs_Kdl1F5JLQHYrj2EeGWCO4w80gYk8JIbKYMZZcZInCagjAqWLXGLGS5jLia6_MhbkY0_yXIg3mNRtXgT6ozC0ouJrQSPvlFwoR6ySb-dL9k1ZoX3F4ipqVSv94SMTQB2AsrXjsJWTzLMwDG2P0ybHL8fcXKKQiZQmp_I4wDjYr5ZYnOXe74aidk0I7KcMjbk8NVFCl-ym85Y6_uEFNK7RCxb_NG8RcyNsz5mGgzoJTvylNETNQquFWwiagBe327iP7LMtcsqK_iuIXnSN0ng5jIOF-EH4IHitPHOu4K-yjZS0c4_V0pVSMrrTmfxdj2ZyaeTIbMylrIdelRW0rMOrtoz240XIh4dFrppRcyvKesG7kv-RUYZrY4x0TGSUqfDQiqEFOgDaC21EzCcJ9qiP0XA0wI3Pk2-e1s.RT7Bx8gNvsZXgkV-xLA-tA
  tls: true
  sni: am2.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-美洲4
  type: http
  server: 77.111.246.14
  port: 443
  username: 0535B93B5824BEBA29C3DD19188B86C2807835B6
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJCY0x6Z1ZrLUduaEhMYjBzSVpQdm1tdXRHeUk0a2FRMU1JT1luaGZ4cEFJIiwieSI6ImRaTzR1VGNKYVU0Wmxqb08wUnBBWEpzVVF0bGs1OXI2YlFlaXdfV2FsUWMifX0.f6XZz8-B3IHyYG6MVqQbAq1h8YuTWSfHMWtU3hi1268CCkv3SlbcLw.9B1nLoltttlKA_Po.76TDzRUS84ZWnvenCiDiUC8SWueygzTNuECLvpfs_Kdl1F5JLQHYrj2EeGWCO4w80gYk8JIbKYMZZcZInCagjAqWLXGLGS5jLia6_MhbkY0_yXIg3mNRtXgT6ozC0ouJrQSPvlFwoR6ySb-dL9k1ZoX3F4ipqVSv94SMTQB2AsrXjsJWTzLMwDG2P0ybHL8fcXKKQiZQmp_I4wDjYr5ZYnOXe74aidk0I7KcMjbk8NVFCl-ym85Y6_uEFNK7RCxb_NG8RcyNsz5mGgzoJTvylNETNQquFWwiagBe327iP7LMtcsqK_iuIXnSN0ng5jIOF-EH4IHitPHOu4K-yjZS0c4_V0pVSMrrTmfxdj2ZyaeTIbMylrIdelRW0rMOrtoz240XIh4dFrppRcyvKesG7kv-RUYZrY4x0TGSUqfDQiqEFOgDaC21EzCcJ9qiP0XA0wI3Pk2-e1s.RT7Bx8gNvsZXgkV-xLA-tA
  tls: true
  sni: am3.sec-tunnel.com
  skip-cert-verify: false
proxy-groups:
- name: 🚀 节点选择
  type: select
  proxies:
  - ♻️ 自动选择
  - 🌏 亚洲节点
  - 🌍 欧洲节点
  - 🌎 美洲节点
  - 🔄 故障转移
  - Opera-亚洲1
  - Opera-亚洲2
  - Opera-欧洲1
  - Opera-欧洲2
  - Opera-欧洲3
  - Opera-欧洲4
  - Opera-美洲1
  - Opera-美洲2
  - Opera-美洲3
  - Opera-美洲4
- name: ♻️ 自动选择
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies: &id001
  - Opera-亚洲1
  - Opera-亚洲2
  - Opera-欧洲1
  - Opera-欧洲2
  - Opera-欧洲3
  - Opera-欧洲4
  - Opera-美洲1
  - Opera-美洲2
  - Opera-美洲3
  - Opera-美洲4
- name: 🌏 亚洲节点
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
  - Opera-亚洲1
  - Opera-亚洲2
- name: 🌍 欧洲节点
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
  - Opera-欧洲1
  - Opera-欧洲2
  - Opera-欧洲3
  - Opera-欧洲4
- name: 🌎 美洲节点
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
  - Opera-美洲1
  - Opera-美洲2
  - Opera-美洲3
  - Opera-美洲4
- name: 🤖 AI服务
  type: select
  proxies:
  - 🚀 节点选择
  - 🌏 亚洲节点
  - 🌎 美洲节点
  - Opera-亚洲1
  - Opera-亚洲2
  - Opera-欧洲1
  - Opera-欧洲2
  - Opera-欧洲3
  - Opera-欧洲4
  - Opera-美洲1
  - Opera-美洲2
  - Opera-美洲3
  - Opera-美洲4
- name: 📹 国际媒体
  type: select
  proxies:
  - 🚀 节点选择
  - ♻️ 自动选择
  - Opera-亚洲1
  - Opera-亚洲2
  - Opera-欧洲1
  - Opera-欧洲2
  - Opera-欧洲3
  - Opera-欧洲4
  - Opera-美洲1
  - Opera-美洲2
  - Opera-美洲3
  - Opera-美洲4
- name: 📲 电报信息
  type: select
  proxies:
  - 🚀 节点选择
  - ♻️ 自动选择
  - Opera-亚洲1
  - Opera-亚洲2
  - Opera-欧洲1
  - Opera-欧洲2
  - Opera-欧洲3
  - Opera-欧洲4
  - Opera-美洲1
  - Opera-美洲2
  - Opera-美洲3
  - Opera-美洲4
- name: 🔄 故障转移
  type: fallback
  url: http://www.gstatic.com/generate_204
  interval: 180
  proxies: *id001
- name: 🎯 全球直连
  type: select
  proxies:
  - DIRECT
- name: 🛑 全球拦截
  type: select
  proxies:
  - REJECT
  - DIRECT
rule-providers:
  LocalAreaNetwork:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
    path: ./ruleset/LocalAreaNetwork.list
  BanAD:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
    path: ./ruleset/BanAD.list
  OpenAi:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
    path: ./ruleset/OpenAi.list
  Telegram:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
    path: ./ruleset/Telegram.list
  YouTube:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
    path: ./ruleset/YouTube.list
  ChinaDomain:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
    path: ./ruleset/ChinaDomain.list
  ChinaCompanyIp:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
    path: ./ruleset/ChinaCompanyIp.list
rules:
- RULE-SET,LocalAreaNetwork,🎯 全球直连
- RULE-SET,BanAD,🛑 全球拦截
- RULE-SET,OpenAi,🤖 AI服务
- RULE-SET,YouTube,📹 国际媒体
- RULE-SET,Telegram,📲 电报信息
- RULE-SET,ChinaDomain,🎯 全球直连
- RULE-SET,ChinaCompanyIp,🎯 全球直连
- GEOIP,CN,🎯 全球直连
- MATCH,🚀 节点选择
