mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
unified-delay: true
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  nameserver:
  - https://223.5.5.5/dns-query
  - https://1.12.12.12/dns-query
  nameserver-policy:
    geosite:cn,private:
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
    geosite:geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
proxies:
- name: Opera-亚洲1
  type: http
  server: 77.111.245.12
  port: 443
  username: E179043ECB6B5138D4487FF196AADD7A74723520
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJMNUxxMTlnNDVkZFE1TjkwWEFPWkdFU2IzS1Nab09ZXzRaLS1UaHJORW9RIiwieSI6IlVlQ0FlYmJEcGo0ZmZ2SW1BR0FITHRzbzBMVmczOG83SjhqTEJmdXZmWncifX0.A0tsc2emygPaGLe0o18U8KOpTDQGQSmTxuH5z0nztScK1cLMK5dBdg.poeMvVRBFzsit7tj.ktvGC9up5D__zAh_2RkMmsmQQf-dpNtBph35OgS2bknvlH8f7dgK4o2hTez1GcrAiYmA2s90-wDqX3eeB0XVGcV9dVn3Un5wndIytvCZ2RBZRTm8uQUWjMw8UhpKRJqGs0_nQyeB7BkNJrnrt3M5xn40ht1otCeU9Q9MjZNBc4VIocYG6knmNLfI3pcSU-XG9FFQeRDdPSZPRbybQeDOnbD6PUwQdZ1UwM5XXJaoD-NRt3yEI507hJ3pNRlisq7QGG2rmXIhRzrD5xI_AaNChDiZfzP72ayZfHm9NNx075DjqI_DZ-lqCF8IciOPk7Nax4e3hn-fmhw6jKoMspayeBqxRO0MiPpZj3ZNRA3xmnHhVFlitWUrkiCRVxU9c-FPVgYHdvMMo6dLx-5LgoTVPHG3uXurKJRLmCFJSf8LeITJZnWu1z21tFck3D0zkZIFDhodD0PirPGh.Oe8gr-0zxcfRgIMfIattDw
  tls: true
  sni: as0.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-欧洲1
  type: http
  server: 77.111.247.23
  port: 443
  username: 02055818E77C7CD3E49C6E0DA4A6FDF19C958280
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxaHZFRGUtY3ZDSWFVRlZwMlRKQ0tfNjdEV2NLc2JJNmZjZGdwQUNCM3c4IiwieSI6IkJFSmswS1FFUzNBeHVWYzMwWVF6VGhvTzFKV1dEZEhSMjdfNFM5eE9maVkifX0.vPyI9PvrSrDp1Lo9_QUEMCikbyNCzwjeHQTfAtGfiGkA-icMdZ4bfw._mwjYIku-n-lqxSR.qxlIsC5HvN7dPtdGNaFKlzUFWuxOuSwwWe4kwUU4dBN1-OzwVBhVpapo540JICS1zg5p-JfsuKBdSSdMW1idWsxWjUurocSmfYh9jrGiKsXyEy5IAsBtIyVjraQCMSUhgIpraNTPc3wH7HlXHhWZnCuJQPb5viXeubi28WigjiXm4VZoOMd7iL9CQdCqtB5eOWL2tdF3iOn7-wWr3szgb7suiyGpQLGV9NdbLarKue4gprx3NVt7YBUkvbV4kvBCOu5o8rQvH2umW6rjKL5cdwS1kDETRoZQdPwBRQSRjDKNJKTZhHoevEUfAuUThENr20_7C4ddGKttQBOKfXRE3a3tjG5uOVejIsay0sGvQQR1w1vL8UppKku6yLqKjuzsCJOaokzpkxY_Sas1vrT0RGcnpuvAWWHujFWUysv_9EOgxuuvncoQ7BQWMvkJc0RIkbQpkog14qjG.9FVNImgn2Ms7JwQygLyuMA
  tls: true
  sni: eu0.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-欧洲2
  type: http
  server: 77.111.247.36
  port: 443
  username: 02055818E77C7CD3E49C6E0DA4A6FDF19C958280
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxaHZFRGUtY3ZDSWFVRlZwMlRKQ0tfNjdEV2NLc2JJNmZjZGdwQUNCM3c4IiwieSI6IkJFSmswS1FFUzNBeHVWYzMwWVF6VGhvTzFKV1dEZEhSMjdfNFM5eE9maVkifX0.vPyI9PvrSrDp1Lo9_QUEMCikbyNCzwjeHQTfAtGfiGkA-icMdZ4bfw._mwjYIku-n-lqxSR.qxlIsC5HvN7dPtdGNaFKlzUFWuxOuSwwWe4kwUU4dBN1-OzwVBhVpapo540JICS1zg5p-JfsuKBdSSdMW1idWsxWjUurocSmfYh9jrGiKsXyEy5IAsBtIyVjraQCMSUhgIpraNTPc3wH7HlXHhWZnCuJQPb5viXeubi28WigjiXm4VZoOMd7iL9CQdCqtB5eOWL2tdF3iOn7-wWr3szgb7suiyGpQLGV9NdbLarKue4gprx3NVt7YBUkvbV4kvBCOu5o8rQvH2umW6rjKL5cdwS1kDETRoZQdPwBRQSRjDKNJKTZhHoevEUfAuUThENr20_7C4ddGKttQBOKfXRE3a3tjG5uOVejIsay0sGvQQR1w1vL8UppKku6yLqKjuzsCJOaokzpkxY_Sas1vrT0RGcnpuvAWWHujFWUysv_9EOgxuuvncoQ7BQWMvkJc0RIkbQpkog14qjG.9FVNImgn2Ms7JwQygLyuMA
  tls: true
  sni: eu1.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-欧洲3
  type: http
  server: 77.111.247.27
  port: 443
  username: 02055818E77C7CD3E49C6E0DA4A6FDF19C958280
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxaHZFRGUtY3ZDSWFVRlZwMlRKQ0tfNjdEV2NLc2JJNmZjZGdwQUNCM3c4IiwieSI6IkJFSmswS1FFUzNBeHVWYzMwWVF6VGhvTzFKV1dEZEhSMjdfNFM5eE9maVkifX0.vPyI9PvrSrDp1Lo9_QUEMCikbyNCzwjeHQTfAtGfiGkA-icMdZ4bfw._mwjYIku-n-lqxSR.qxlIsC5HvN7dPtdGNaFKlzUFWuxOuSwwWe4kwUU4dBN1-OzwVBhVpapo540JICS1zg5p-JfsuKBdSSdMW1idWsxWjUurocSmfYh9jrGiKsXyEy5IAsBtIyVjraQCMSUhgIpraNTPc3wH7HlXHhWZnCuJQPb5viXeubi28WigjiXm4VZoOMd7iL9CQdCqtB5eOWL2tdF3iOn7-wWr3szgb7suiyGpQLGV9NdbLarKue4gprx3NVt7YBUkvbV4kvBCOu5o8rQvH2umW6rjKL5cdwS1kDETRoZQdPwBRQSRjDKNJKTZhHoevEUfAuUThENr20_7C4ddGKttQBOKfXRE3a3tjG5uOVejIsay0sGvQQR1w1vL8UppKku6yLqKjuzsCJOaokzpkxY_Sas1vrT0RGcnpuvAWWHujFWUysv_9EOgxuuvncoQ7BQWMvkJc0RIkbQpkog14qjG.9FVNImgn2Ms7JwQygLyuMA
  tls: true
  sni: eu2.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-欧洲4
  type: http
  server: 77.111.247.37
  port: 443
  username: 02055818E77C7CD3E49C6E0DA4A6FDF19C958280
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxaHZFRGUtY3ZDSWFVRlZwMlRKQ0tfNjdEV2NLc2JJNmZjZGdwQUNCM3c4IiwieSI6IkJFSmswS1FFUzNBeHVWYzMwWVF6VGhvTzFKV1dEZEhSMjdfNFM5eE9maVkifX0.vPyI9PvrSrDp1Lo9_QUEMCikbyNCzwjeHQTfAtGfiGkA-icMdZ4bfw._mwjYIku-n-lqxSR.qxlIsC5HvN7dPtdGNaFKlzUFWuxOuSwwWe4kwUU4dBN1-OzwVBhVpapo540JICS1zg5p-JfsuKBdSSdMW1idWsxWjUurocSmfYh9jrGiKsXyEy5IAsBtIyVjraQCMSUhgIpraNTPc3wH7HlXHhWZnCuJQPb5viXeubi28WigjiXm4VZoOMd7iL9CQdCqtB5eOWL2tdF3iOn7-wWr3szgb7suiyGpQLGV9NdbLarKue4gprx3NVt7YBUkvbV4kvBCOu5o8rQvH2umW6rjKL5cdwS1kDETRoZQdPwBRQSRjDKNJKTZhHoevEUfAuUThENr20_7C4ddGKttQBOKfXRE3a3tjG5uOVejIsay0sGvQQR1w1vL8UppKku6yLqKjuzsCJOaokzpkxY_Sas1vrT0RGcnpuvAWWHujFWUysv_9EOgxuuvncoQ7BQWMvkJc0RIkbQpkog14qjG.9FVNImgn2Ms7JwQygLyuMA
  tls: true
  sni: eu3.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-美洲1
  type: http
  server: 77.111.246.40
  port: 443
  username: 41D14B560F714D5D55C5DD8FAAFED2BFB807B018
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxX21nNm1pNzNLUTBXQVFMSXc0a0JhMkRmTTNlbjlNNTVsTk0xYnFnamtBIiwieSI6IjNNVnF4dUFTVE9PcXRWUDlWOXhvV2YyZ2F1aGptUGtvUE5ZYUw3NkZ4Mm8ifX0.H2cHbE-ydoM2n1ZgKJR1Gcz38ROs6hX0DVjmx5IKwidXRSM1h1BA_Q.Q8oJ4v6XI5OIrxMw.jjNLFHVZQmUNXVEi2XqRj5abTsty6ZoH0foOk6WhY0_5UVB7IGJKr-ufp20GILFOmi2dpSILzxn_wN7_lKTtEI-k7e7Z7hXxxPsh-EYYXTfnBg8DDT89kj6-Tt59WBvdjDwgKm4I8VshGQ7t5D757Ig3AOh0uTNMBzPb_Hy-Din8I-xxaziTck_JId66YWac7ydLdvXlS0xhsLU5akjaVTTk_F8G1abz_3dCkhEVj0Vk3f9u6ehJ8IuzekFIDYpGuXzT5uZT-U4M8KDVrUxtePV44WNJGZVHjyCAG8GEc6a4cqwRtHrl0zoA-CdNeMocu3LicPPyDUVtOz4gxr73rYTzz5gbVt8bnZf0bjig5FkFHEaGjUB-wPGBjbjSq9NpiFwbrWU1DugT8HlEN_i3Jvfa3Pak4lZOv4TSMGXIkjCIcFZfKG0gAfUsOHhw2GiBt1Qs2Ye-ydIE.9CX2S5v7wf_FYAFuujjjbA
  tls: true
  sni: am0.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-美洲2
  type: http
  server: 77.111.246.51
  port: 443
  username: 41D14B560F714D5D55C5DD8FAAFED2BFB807B018
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxX21nNm1pNzNLUTBXQVFMSXc0a0JhMkRmTTNlbjlNNTVsTk0xYnFnamtBIiwieSI6IjNNVnF4dUFTVE9PcXRWUDlWOXhvV2YyZ2F1aGptUGtvUE5ZYUw3NkZ4Mm8ifX0.H2cHbE-ydoM2n1ZgKJR1Gcz38ROs6hX0DVjmx5IKwidXRSM1h1BA_Q.Q8oJ4v6XI5OIrxMw.jjNLFHVZQmUNXVEi2XqRj5abTsty6ZoH0foOk6WhY0_5UVB7IGJKr-ufp20GILFOmi2dpSILzxn_wN7_lKTtEI-k7e7Z7hXxxPsh-EYYXTfnBg8DDT89kj6-Tt59WBvdjDwgKm4I8VshGQ7t5D757Ig3AOh0uTNMBzPb_Hy-Din8I-xxaziTck_JId66YWac7ydLdvXlS0xhsLU5akjaVTTk_F8G1abz_3dCkhEVj0Vk3f9u6ehJ8IuzekFIDYpGuXzT5uZT-U4M8KDVrUxtePV44WNJGZVHjyCAG8GEc6a4cqwRtHrl0zoA-CdNeMocu3LicPPyDUVtOz4gxr73rYTzz5gbVt8bnZf0bjig5FkFHEaGjUB-wPGBjbjSq9NpiFwbrWU1DugT8HlEN_i3Jvfa3Pak4lZOv4TSMGXIkjCIcFZfKG0gAfUsOHhw2GiBt1Qs2Ye-ydIE.9CX2S5v7wf_FYAFuujjjbA
  tls: true
  sni: am1.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-美洲3
  type: http
  server: 77.111.246.26
  port: 443
  username: 41D14B560F714D5D55C5DD8FAAFED2BFB807B018
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxX21nNm1pNzNLUTBXQVFMSXc0a0JhMkRmTTNlbjlNNTVsTk0xYnFnamtBIiwieSI6IjNNVnF4dUFTVE9PcXRWUDlWOXhvV2YyZ2F1aGptUGtvUE5ZYUw3NkZ4Mm8ifX0.H2cHbE-ydoM2n1ZgKJR1Gcz38ROs6hX0DVjmx5IKwidXRSM1h1BA_Q.Q8oJ4v6XI5OIrxMw.jjNLFHVZQmUNXVEi2XqRj5abTsty6ZoH0foOk6WhY0_5UVB7IGJKr-ufp20GILFOmi2dpSILzxn_wN7_lKTtEI-k7e7Z7hXxxPsh-EYYXTfnBg8DDT89kj6-Tt59WBvdjDwgKm4I8VshGQ7t5D757Ig3AOh0uTNMBzPb_Hy-Din8I-xxaziTck_JId66YWac7ydLdvXlS0xhsLU5akjaVTTk_F8G1abz_3dCkhEVj0Vk3f9u6ehJ8IuzekFIDYpGuXzT5uZT-U4M8KDVrUxtePV44WNJGZVHjyCAG8GEc6a4cqwRtHrl0zoA-CdNeMocu3LicPPyDUVtOz4gxr73rYTzz5gbVt8bnZf0bjig5FkFHEaGjUB-wPGBjbjSq9NpiFwbrWU1DugT8HlEN_i3Jvfa3Pak4lZOv4TSMGXIkjCIcFZfKG0gAfUsOHhw2GiBt1Qs2Ye-ydIE.9CX2S5v7wf_FYAFuujjjbA
  tls: true
  sni: am2.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-美洲4
  type: http
  server: 77.111.246.60
  port: 443
  username: 41D14B560F714D5D55C5DD8FAAFED2BFB807B018
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJxX21nNm1pNzNLUTBXQVFMSXc0a0JhMkRmTTNlbjlNNTVsTk0xYnFnamtBIiwieSI6IjNNVnF4dUFTVE9PcXRWUDlWOXhvV2YyZ2F1aGptUGtvUE5ZYUw3NkZ4Mm8ifX0.H2cHbE-ydoM2n1ZgKJR1Gcz38ROs6hX0DVjmx5IKwidXRSM1h1BA_Q.Q8oJ4v6XI5OIrxMw.jjNLFHVZQmUNXVEi2XqRj5abTsty6ZoH0foOk6WhY0_5UVB7IGJKr-ufp20GILFOmi2dpSILzxn_wN7_lKTtEI-k7e7Z7hXxxPsh-EYYXTfnBg8DDT89kj6-Tt59WBvdjDwgKm4I8VshGQ7t5D757Ig3AOh0uTNMBzPb_Hy-Din8I-xxaziTck_JId66YWac7ydLdvXlS0xhsLU5akjaVTTk_F8G1abz_3dCkhEVj0Vk3f9u6ehJ8IuzekFIDYpGuXzT5uZT-U4M8KDVrUxtePV44WNJGZVHjyCAG8GEc6a4cqwRtHrl0zoA-CdNeMocu3LicPPyDUVtOz4gxr73rYTzz5gbVt8bnZf0bjig5FkFHEaGjUB-wPGBjbjSq9NpiFwbrWU1DugT8HlEN_i3Jvfa3Pak4lZOv4TSMGXIkjCIcFZfKG0gAfUsOHhw2GiBt1Qs2Ye-ydIE.9CX2S5v7wf_FYAFuujjjbA
  tls: true
  sni: am3.sec-tunnel.com
  skip-cert-verify: false
proxy-groups:
- name: 🚀 节点选择
  type: select
  proxies:
  - ♻️ 自动选择
  - 🌏 亚洲节点
  - 🌍 欧洲节点
  - 🌎 美洲节点
  - 🔄 故障转移
  - Opera-亚洲1
  - Opera-欧洲1
  - Opera-欧洲2
  - Opera-欧洲3
  - Opera-欧洲4
  - Opera-美洲1
  - Opera-美洲2
  - Opera-美洲3
  - Opera-美洲4
- name: ♻️ 自动选择
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies: &id001
  - Opera-亚洲1
  - Opera-欧洲1
  - Opera-欧洲2
  - Opera-欧洲3
  - Opera-欧洲4
  - Opera-美洲1
  - Opera-美洲2
  - Opera-美洲3
  - Opera-美洲4
- name: 🌏 亚洲节点
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
  - Opera-亚洲1
- name: 🌍 欧洲节点
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
  - Opera-欧洲1
  - Opera-欧洲2
  - Opera-欧洲3
  - Opera-欧洲4
- name: 🌎 美洲节点
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
  - Opera-美洲1
  - Opera-美洲2
  - Opera-美洲3
  - Opera-美洲4
- name: 🤖 AI服务
  type: select
  proxies:
  - 🚀 节点选择
  - 🌏 亚洲节点
  - 🌎 美洲节点
  - Opera-亚洲1
  - Opera-欧洲1
  - Opera-欧洲2
  - Opera-欧洲3
  - Opera-欧洲4
  - Opera-美洲1
  - Opera-美洲2
  - Opera-美洲3
  - Opera-美洲4
- name: 📹 国际媒体
  type: select
  proxies:
  - 🚀 节点选择
  - ♻️ 自动选择
  - Opera-亚洲1
  - Opera-欧洲1
  - Opera-欧洲2
  - Opera-欧洲3
  - Opera-欧洲4
  - Opera-美洲1
  - Opera-美洲2
  - Opera-美洲3
  - Opera-美洲4
- name: 📲 电报信息
  type: select
  proxies:
  - 🚀 节点选择
  - ♻️ 自动选择
  - Opera-亚洲1
  - Opera-欧洲1
  - Opera-欧洲2
  - Opera-欧洲3
  - Opera-欧洲4
  - Opera-美洲1
  - Opera-美洲2
  - Opera-美洲3
  - Opera-美洲4
- name: 🔄 故障转移
  type: fallback
  url: http://www.gstatic.com/generate_204
  interval: 180
  proxies: *id001
- name: 🎯 全球直连
  type: select
  proxies:
  - DIRECT
- name: 🛑 全球拦截
  type: select
  proxies:
  - REJECT
  - DIRECT
rule-providers:
  LocalAreaNetwork:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
    path: ./ruleset/LocalAreaNetwork.list
  BanAD:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
    path: ./ruleset/BanAD.list
  OpenAi:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
    path: ./ruleset/OpenAi.list
  Telegram:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
    path: ./ruleset/Telegram.list
  YouTube:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
    path: ./ruleset/YouTube.list
  ChinaDomain:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
    path: ./ruleset/ChinaDomain.list
  ChinaCompanyIp:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
    path: ./ruleset/ChinaCompanyIp.list
rules:
- RULE-SET,LocalAreaNetwork,🎯 全球直连
- RULE-SET,BanAD,🛑 全球拦截
- RULE-SET,OpenAi,🤖 AI服务
- RULE-SET,YouTube,📹 国际媒体
- RULE-SET,Telegram,📲 电报信息
- RULE-SET,ChinaDomain,🎯 全球直连
- RULE-SET,ChinaCompanyIp,🎯 全球直连
- GEOIP,CN,🎯 全球直连
- MATCH,🚀 节点选择
