mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
unified-delay: true
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  nameserver:
  - https://223.5.5.5/dns-query
  - https://1.12.12.12/dns-query
  nameserver-policy:
    geosite:cn,private:
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
    geosite:geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
proxies:
- name: Opera-亚洲1
  type: http
  server: 77.111.245.15
  port: 443
  username: 7CB04B2CC6244188FEC9F0B428641E59D5D14427
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI4UU8teUw1NjI3SDFZRVVQY1ZKOHB1OFNuSWZiT0RsSzRTSnZ3RU5RNkZ3IiwieSI6IjB4NWFrZ0dmLWtxMEV1eks5NV9hV2xpaWxKT05yWXhhRjNPUEc4LWJiVHcifX0.lKoM0z-1P10W_FdNWLW8By8Ps_ynZQQcSRw_zCi53CF9yohCa_5LkQ.QLHMjPa4_lsmWOrr.xqE2fxDCxc_m3wOmQ2yS0BrmQeo2rjdNg8Tj-AZhv1q2_DhkNSxUS-EIpfH49DEc-eGolDnw8iO4snER-EYGv2cD8-MvHdOzpeSjNsdh3T5HbnosLtXNdCvNP_PKc-hl0z47C-3Z-lbSXlwHWGa8aWvCuM8Sd5Uwmp70S1-MSAF4xTbTl3xNk_DNuakpNTJcr1LeIpF2J5azmLOFAbfXlxTC5OyaQ314C5WRQejhrmDhfkELPmq4tHUXwj7TFuU3U4T85sv0kXKxzOG6_p8H9al6Tyzem_HD80mgh-f80FUSxocc6zPSt_6MNHWct-5yOFh6Gm5DQnH_nkxwp4fHFAvMFJZ1lUteYBdBc4QOTFCOOKvbzL49Uw40evfcbQvX0phGHx8W-k_uAMu_1mogRFthWpcaEhHM8rL5bXfyYEkQvxPTC65M2kbIpSBCk-wuDhoTIoV4EjHf8TQ.UBD9fFZTzyZYNiMb8JhZCw
  tls: true
  sni: as0.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-欧洲1
  type: http
  server: 77.111.247.80
  port: 443
  username: 30DFB54BC679487E1E6019CE13D004F93CFB22D2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJXMWxCSGpXRFhRZDdEMDdXNS05dmJZUGx1eXU3bHJzcTJwZjZkcGpxLVl3IiwieSI6ImRDTE5ERTl4TW1CckQyTTg3aUd3YVczSkdiV2RRZmFPb29fZU84dnNnczgifX0.385J6DGezTnO0qNwmA62dI2gQyj-NvF9UArB1spISroGxUFJIXmuWA.HQRogDOR04dLncSG.7Ju8SdHNe-2Y1iWLG5dPZbhCGmkSckZNR4zIZr4KG17-WpKmnyMWbPBacalYPDkNZcGwjdjseZSgRaguu3DCOZFP2WuwN4gd-GcCWdPgCUNthiucsYVYsv1BS8uLVBQMPpE84lqC05C2aW-S39PqC6VDAGW40wXYbxr-iwxSmMG95Cd1lI7dPFhIi8NGNVidu71ecXZoFo6aB-PYH-_jtBZx8kAdTFs1R_Pfqf-Fby5fVhQM6Xpjxn7I0Ayhd8iL0X8Hm6ddViXG1KpJn99S2DRMWgKxZmrEh_AuvrM-OMT3sog64T-0MioOtYgY8Z29lh2dQbP2rpywvuSNET-90ybS2I8MeZAuCxVLwByJNcDqwlEVkrRdRzJeggFb1vPLYq12cPFbbRMQFAoq9dpd6ZAL_chXpqMsAdh_B8601PwSudVQ9YxLW8wfMPoLeTfBDVNGWoR7tS7bUF4.y-6nDNVgvItSMMrmAP7uEw
  tls: true
  sni: eu0.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-欧洲2
  type: http
  server: 77.111.247.79
  port: 443
  username: 30DFB54BC679487E1E6019CE13D004F93CFB22D2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJXMWxCSGpXRFhRZDdEMDdXNS05dmJZUGx1eXU3bHJzcTJwZjZkcGpxLVl3IiwieSI6ImRDTE5ERTl4TW1CckQyTTg3aUd3YVczSkdiV2RRZmFPb29fZU84dnNnczgifX0.385J6DGezTnO0qNwmA62dI2gQyj-NvF9UArB1spISroGxUFJIXmuWA.HQRogDOR04dLncSG.7Ju8SdHNe-2Y1iWLG5dPZbhCGmkSckZNR4zIZr4KG17-WpKmnyMWbPBacalYPDkNZcGwjdjseZSgRaguu3DCOZFP2WuwN4gd-GcCWdPgCUNthiucsYVYsv1BS8uLVBQMPpE84lqC05C2aW-S39PqC6VDAGW40wXYbxr-iwxSmMG95Cd1lI7dPFhIi8NGNVidu71ecXZoFo6aB-PYH-_jtBZx8kAdTFs1R_Pfqf-Fby5fVhQM6Xpjxn7I0Ayhd8iL0X8Hm6ddViXG1KpJn99S2DRMWgKxZmrEh_AuvrM-OMT3sog64T-0MioOtYgY8Z29lh2dQbP2rpywvuSNET-90ybS2I8MeZAuCxVLwByJNcDqwlEVkrRdRzJeggFb1vPLYq12cPFbbRMQFAoq9dpd6ZAL_chXpqMsAdh_B8601PwSudVQ9YxLW8wfMPoLeTfBDVNGWoR7tS7bUF4.y-6nDNVgvItSMMrmAP7uEw
  tls: true
  sni: eu1.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-欧洲3
  type: http
  server: 77.111.247.42
  port: 443
  username: 30DFB54BC679487E1E6019CE13D004F93CFB22D2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJXMWxCSGpXRFhRZDdEMDdXNS05dmJZUGx1eXU3bHJzcTJwZjZkcGpxLVl3IiwieSI6ImRDTE5ERTl4TW1CckQyTTg3aUd3YVczSkdiV2RRZmFPb29fZU84dnNnczgifX0.385J6DGezTnO0qNwmA62dI2gQyj-NvF9UArB1spISroGxUFJIXmuWA.HQRogDOR04dLncSG.7Ju8SdHNe-2Y1iWLG5dPZbhCGmkSckZNR4zIZr4KG17-WpKmnyMWbPBacalYPDkNZcGwjdjseZSgRaguu3DCOZFP2WuwN4gd-GcCWdPgCUNthiucsYVYsv1BS8uLVBQMPpE84lqC05C2aW-S39PqC6VDAGW40wXYbxr-iwxSmMG95Cd1lI7dPFhIi8NGNVidu71ecXZoFo6aB-PYH-_jtBZx8kAdTFs1R_Pfqf-Fby5fVhQM6Xpjxn7I0Ayhd8iL0X8Hm6ddViXG1KpJn99S2DRMWgKxZmrEh_AuvrM-OMT3sog64T-0MioOtYgY8Z29lh2dQbP2rpywvuSNET-90ybS2I8MeZAuCxVLwByJNcDqwlEVkrRdRzJeggFb1vPLYq12cPFbbRMQFAoq9dpd6ZAL_chXpqMsAdh_B8601PwSudVQ9YxLW8wfMPoLeTfBDVNGWoR7tS7bUF4.y-6nDNVgvItSMMrmAP7uEw
  tls: true
  sni: eu2.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-欧洲4
  type: http
  server: 77.111.244.210
  port: 443
  username: 30DFB54BC679487E1E6019CE13D004F93CFB22D2
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJXMWxCSGpXRFhRZDdEMDdXNS05dmJZUGx1eXU3bHJzcTJwZjZkcGpxLVl3IiwieSI6ImRDTE5ERTl4TW1CckQyTTg3aUd3YVczSkdiV2RRZmFPb29fZU84dnNnczgifX0.385J6DGezTnO0qNwmA62dI2gQyj-NvF9UArB1spISroGxUFJIXmuWA.HQRogDOR04dLncSG.7Ju8SdHNe-2Y1iWLG5dPZbhCGmkSckZNR4zIZr4KG17-WpKmnyMWbPBacalYPDkNZcGwjdjseZSgRaguu3DCOZFP2WuwN4gd-GcCWdPgCUNthiucsYVYsv1BS8uLVBQMPpE84lqC05C2aW-S39PqC6VDAGW40wXYbxr-iwxSmMG95Cd1lI7dPFhIi8NGNVidu71ecXZoFo6aB-PYH-_jtBZx8kAdTFs1R_Pfqf-Fby5fVhQM6Xpjxn7I0Ayhd8iL0X8Hm6ddViXG1KpJn99S2DRMWgKxZmrEh_AuvrM-OMT3sog64T-0MioOtYgY8Z29lh2dQbP2rpywvuSNET-90ybS2I8MeZAuCxVLwByJNcDqwlEVkrRdRzJeggFb1vPLYq12cPFbbRMQFAoq9dpd6ZAL_chXpqMsAdh_B8601PwSudVQ9YxLW8wfMPoLeTfBDVNGWoR7tS7bUF4.y-6nDNVgvItSMMrmAP7uEw
  tls: true
  sni: eu3.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-美洲1
  type: http
  server: 77.111.246.45
  port: 443
  username: 988EBB97FCF20990828D2763E7836A7C4620B466
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ4WDBnZTFnZ08zZGlBQUluQVB2RTJ1OWI3WHVEZ1RJbTllZUZoUmhmek1vIiwieSI6IlROUE5qQzBCbTFyM2JJWEZqZnVXbE1LOHd3VGx3YTBST0hmTDhBMm1mZFkifX0.5lm8V4cokhUzwMSZB1cx0p78ZNDTUDNFZN-7LEguUD2OhijE1vUU1w.RaB6vCVvfHtYxsfj.sfzU8YJGl_-hwEoztHmD5H4l37mYnAaN1iUzfWyYGRfTMwb7DtOkQlGI8bolxtzsYLk3EKF2p8YOgnoGsQsHuqcImixecVjrWCzAQLl8Gx5CaSVDwTogdTNYTQnef3Tjc9Q5mi63paRm9Kq85aSqs_AN3SZNBTefmjFA81tU1qqZe7zxgNqaQRY-20jHX-7vNNuGHGUj36U9Bit38QCSABjPvDS1ZnH0JaJ0K06AwODygZUXdkpsjo4BBNcqlm2o04UO9shQ1Fv9Zp2WmMovg_FHH9182WUv_ps-MD8aJT4OtOpfm7xy7JF3AbsJksI2Q91Upto8_HRHmYGWxf4GPUUCPD7Cuac0vBo_7OeMbMvxKn7G4xY2tkKGKzXBXezrcNXHMF-6ie9mbvBB-uzCPYiqKNvIDz3pjl6d47Jt7A-c9j6PaWpcGQFVlckhUJQtrnGuSgT_CmFVsFA.FmKWhMq0ntkdDaufCw4NmQ
  tls: true
  sni: am0.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-美洲2
  type: http
  server: 77.111.246.51
  port: 443
  username: 988EBB97FCF20990828D2763E7836A7C4620B466
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ4WDBnZTFnZ08zZGlBQUluQVB2RTJ1OWI3WHVEZ1RJbTllZUZoUmhmek1vIiwieSI6IlROUE5qQzBCbTFyM2JJWEZqZnVXbE1LOHd3VGx3YTBST0hmTDhBMm1mZFkifX0.5lm8V4cokhUzwMSZB1cx0p78ZNDTUDNFZN-7LEguUD2OhijE1vUU1w.RaB6vCVvfHtYxsfj.sfzU8YJGl_-hwEoztHmD5H4l37mYnAaN1iUzfWyYGRfTMwb7DtOkQlGI8bolxtzsYLk3EKF2p8YOgnoGsQsHuqcImixecVjrWCzAQLl8Gx5CaSVDwTogdTNYTQnef3Tjc9Q5mi63paRm9Kq85aSqs_AN3SZNBTefmjFA81tU1qqZe7zxgNqaQRY-20jHX-7vNNuGHGUj36U9Bit38QCSABjPvDS1ZnH0JaJ0K06AwODygZUXdkpsjo4BBNcqlm2o04UO9shQ1Fv9Zp2WmMovg_FHH9182WUv_ps-MD8aJT4OtOpfm7xy7JF3AbsJksI2Q91Upto8_HRHmYGWxf4GPUUCPD7Cuac0vBo_7OeMbMvxKn7G4xY2tkKGKzXBXezrcNXHMF-6ie9mbvBB-uzCPYiqKNvIDz3pjl6d47Jt7A-c9j6PaWpcGQFVlckhUJQtrnGuSgT_CmFVsFA.FmKWhMq0ntkdDaufCw4NmQ
  tls: true
  sni: am1.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-美洲3
  type: http
  server: 77.111.246.64
  port: 443
  username: 988EBB97FCF20990828D2763E7836A7C4620B466
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ4WDBnZTFnZ08zZGlBQUluQVB2RTJ1OWI3WHVEZ1RJbTllZUZoUmhmek1vIiwieSI6IlROUE5qQzBCbTFyM2JJWEZqZnVXbE1LOHd3VGx3YTBST0hmTDhBMm1mZFkifX0.5lm8V4cokhUzwMSZB1cx0p78ZNDTUDNFZN-7LEguUD2OhijE1vUU1w.RaB6vCVvfHtYxsfj.sfzU8YJGl_-hwEoztHmD5H4l37mYnAaN1iUzfWyYGRfTMwb7DtOkQlGI8bolxtzsYLk3EKF2p8YOgnoGsQsHuqcImixecVjrWCzAQLl8Gx5CaSVDwTogdTNYTQnef3Tjc9Q5mi63paRm9Kq85aSqs_AN3SZNBTefmjFA81tU1qqZe7zxgNqaQRY-20jHX-7vNNuGHGUj36U9Bit38QCSABjPvDS1ZnH0JaJ0K06AwODygZUXdkpsjo4BBNcqlm2o04UO9shQ1Fv9Zp2WmMovg_FHH9182WUv_ps-MD8aJT4OtOpfm7xy7JF3AbsJksI2Q91Upto8_HRHmYGWxf4GPUUCPD7Cuac0vBo_7OeMbMvxKn7G4xY2tkKGKzXBXezrcNXHMF-6ie9mbvBB-uzCPYiqKNvIDz3pjl6d47Jt7A-c9j6PaWpcGQFVlckhUJQtrnGuSgT_CmFVsFA.FmKWhMq0ntkdDaufCw4NmQ
  tls: true
  sni: am2.sec-tunnel.com
  skip-cert-verify: false
- name: Opera-美洲4
  type: http
  server: 77.111.246.63
  port: 443
  username: 988EBB97FCF20990828D2763E7836A7C4620B466
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJ4WDBnZTFnZ08zZGlBQUluQVB2RTJ1OWI3WHVEZ1RJbTllZUZoUmhmek1vIiwieSI6IlROUE5qQzBCbTFyM2JJWEZqZnVXbE1LOHd3VGx3YTBST0hmTDhBMm1mZFkifX0.5lm8V4cokhUzwMSZB1cx0p78ZNDTUDNFZN-7LEguUD2OhijE1vUU1w.RaB6vCVvfHtYxsfj.sfzU8YJGl_-hwEoztHmD5H4l37mYnAaN1iUzfWyYGRfTMwb7DtOkQlGI8bolxtzsYLk3EKF2p8YOgnoGsQsHuqcImixecVjrWCzAQLl8Gx5CaSVDwTogdTNYTQnef3Tjc9Q5mi63paRm9Kq85aSqs_AN3SZNBTefmjFA81tU1qqZe7zxgNqaQRY-20jHX-7vNNuGHGUj36U9Bit38QCSABjPvDS1ZnH0JaJ0K06AwODygZUXdkpsjo4BBNcqlm2o04UO9shQ1Fv9Zp2WmMovg_FHH9182WUv_ps-MD8aJT4OtOpfm7xy7JF3AbsJksI2Q91Upto8_HRHmYGWxf4GPUUCPD7Cuac0vBo_7OeMbMvxKn7G4xY2tkKGKzXBXezrcNXHMF-6ie9mbvBB-uzCPYiqKNvIDz3pjl6d47Jt7A-c9j6PaWpcGQFVlckhUJQtrnGuSgT_CmFVsFA.FmKWhMq0ntkdDaufCw4NmQ
  tls: true
  sni: am3.sec-tunnel.com
  skip-cert-verify: false
proxy-groups:
- name: 🚀 节点选择
  type: select
  proxies:
  - ♻️ 自动选择
  - 🌏 亚洲节点
  - 🌍 欧洲节点
  - 🌎 美洲节点
  - 🔄 故障转移
  - Opera-亚洲1
  - Opera-欧洲1
  - Opera-欧洲2
  - Opera-欧洲3
  - Opera-欧洲4
  - Opera-美洲1
  - Opera-美洲2
  - Opera-美洲3
  - Opera-美洲4
- name: ♻️ 自动选择
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies: &id001
  - Opera-亚洲1
  - Opera-欧洲1
  - Opera-欧洲2
  - Opera-欧洲3
  - Opera-欧洲4
  - Opera-美洲1
  - Opera-美洲2
  - Opera-美洲3
  - Opera-美洲4
- name: 🌏 亚洲节点
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
  - Opera-亚洲1
- name: 🌍 欧洲节点
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
  - Opera-欧洲1
  - Opera-欧洲2
  - Opera-欧洲3
  - Opera-欧洲4
- name: 🌎 美洲节点
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
  - Opera-美洲1
  - Opera-美洲2
  - Opera-美洲3
  - Opera-美洲4
- name: 🤖 AI服务
  type: select
  proxies:
  - 🚀 节点选择
  - 🌏 亚洲节点
  - 🌎 美洲节点
  - Opera-亚洲1
  - Opera-欧洲1
  - Opera-欧洲2
  - Opera-欧洲3
  - Opera-欧洲4
  - Opera-美洲1
  - Opera-美洲2
  - Opera-美洲3
  - Opera-美洲4
- name: 📹 国际媒体
  type: select
  proxies:
  - 🚀 节点选择
  - ♻️ 自动选择
  - Opera-亚洲1
  - Opera-欧洲1
  - Opera-欧洲2
  - Opera-欧洲3
  - Opera-欧洲4
  - Opera-美洲1
  - Opera-美洲2
  - Opera-美洲3
  - Opera-美洲4
- name: 📲 电报信息
  type: select
  proxies:
  - 🚀 节点选择
  - ♻️ 自动选择
  - Opera-亚洲1
  - Opera-欧洲1
  - Opera-欧洲2
  - Opera-欧洲3
  - Opera-欧洲4
  - Opera-美洲1
  - Opera-美洲2
  - Opera-美洲3
  - Opera-美洲4
- name: 🔄 故障转移
  type: fallback
  url: http://www.gstatic.com/generate_204
  interval: 180
  proxies: *id001
- name: 🎯 全球直连
  type: select
  proxies:
  - DIRECT
- name: 🛑 全球拦截
  type: select
  proxies:
  - REJECT
  - DIRECT
rule-providers:
  LocalAreaNetwork:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
    path: ./ruleset/LocalAreaNetwork.list
  BanAD:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
    path: ./ruleset/BanAD.list
  OpenAi:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
    path: ./ruleset/OpenAi.list
  Telegram:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
    path: ./ruleset/Telegram.list
  YouTube:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
    path: ./ruleset/YouTube.list
  ChinaDomain:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
    path: ./ruleset/ChinaDomain.list
  ChinaCompanyIp:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
    path: ./ruleset/ChinaCompanyIp.list
rules:
- RULE-SET,LocalAreaNetwork,🎯 全球直连
- RULE-SET,BanAD,🛑 全球拦截
- RULE-SET,OpenAi,🤖 AI服务
- RULE-SET,YouTube,📹 国际媒体
- RULE-SET,Telegram,📲 电报信息
- RULE-SET,ChinaDomain,🎯 全球直连
- RULE-SET,ChinaCompanyIp,🎯 全球直连
- GEOIP,CN,🎯 全球直连
- MATCH,🚀 节点选择
